### ISSUE TITLE
SPICE Diode Level 1

### ISSUE THREAD

**Issue by jcornau** [aesim-tech/simba-project#436]
Support SPICE diode model.  Example:

```spice
d(is=200n bv=2590 EG=2 n=1.2
+	rs=0.02  trs1=0.0001  trs2=-0.0001 Tnom=10
+	tt=0.1n ibv=800u Xti=0.23 level=1)
```

```[tasklist]
### Tasks
- [x] Define the implementation of the model with the equations
- [x] Develop the model
- [x] Test and validation
- [ ] Add documentation
```
